eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8766
  
spring:
  application:
    name: service-zuul

#首先指定服务注册中心的地址为http://localhost:8761/eureka/，服务的端口为8769，服务名为service-zuul；
#以/feign/ 开头的请求都转发给eureka-feign-consume服务；以/ribbon/开头的请求都转发给eureka-ribbon-consume服务；
zuul:
  routes:
    feign-service:
      path: /feign/**
      service-id: eureka-feign-consume
    ribbon-service:
      path: /ribbon/**
      service-id: eureka-ribbon-consume