spring:
  application:
    name: service-turbine
server:
  port: 8773
  connection-timeout: 60000

security:
  basic:
    enabled: false
turbine:
  app-config: service-ribbon-consume,service-ribbon-turbine-consume
  cluster-name-expression: "'default'"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
